services:
  - type: web
    name: sentiment-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn deploy_endpoint:app --host 0.0.0.0 --port 10000
    plan: free